In [86]:
import pandas as pd
import numpy as np
from sklearn.model_selection import *
from sklearn.preprocessing import *
import torch
import torch.nn as nn
import torch.optim as optim

train_data = pd.read_csv("C:/Users/wq188/OneDrive/바탕 화면/강의자료/딥러닝프로그래밍/딥러닝 프로젝트/deep-learning-programing-project/train_data.csv")

In [55]:
train_data.head()

LABEL   FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6  FLUX.7  \
0      2    93.85    83.81    20.10   -26.98   -39.56  -124.71 -135.18   
1      2   -38.88   -33.83   -58.54   -40.09   -79.31   -72.81  -86.55   
2      2   532.64   535.92   513.73   496.92   456.45   466.00  464.50   
3      2   326.52   347.39   302.35   298.13   317.74   312.70  322.33   
4      2 -1107.21 -1112.59 -1118.95 -1095.10 -1057.55 -1034.48 -998.34   

    FLUX.8  FLUX.9  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0   -96.27  -79.89  ...     -78.07    -102.15    -102.15      25.13   
1   -85.33  -83.97  ...      -3.28     -32.21     -32.21     -24.89   
2   486.39  436.56  ...     -71.69      13.31      13.31     -29.89   
3   311.31  312.42  ...       5.71      -3.73      -3.73      30.05   
4 -1022.71 -989.57  ...    -594.37    -401.66    -401.66    -357.24   

   FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0      48.57      92.54      39.32      61.42       5.08     -39.54  
1      -4.86       0.76     -11.70       6.46      16.00      19.93  
2     -20.88       5.06     -11.80     -28.91     -70.02     -96.67  
3      20.03     -12.67      -8.77     -17.31     -17.35      13.98  
4    -443.76    -438.54    -399.71    -384.65    -411.79    -510.54  

[5 rows x 3198 columns]

In [56]:
train_data.isnull().sum()

LABEL        0
FLUX.1       0
FLUX.2       0
FLUX.3       0
FLUX.4       0
            ..
FLUX.3193    0
FLUX.3194    0
FLUX.3195    0
FLUX.3196    0
FLUX.3197    0
Length: 3198, dtype: int64

In [57]:
flux_columns = train_data.columns[1:]
X = train_data[flux_columns]

y = train_data['LABEL']

In [58]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

array([[-0.00235557, -0.00205404, -0.00579778, ...,  0.0341983 ,
         0.02736753,  0.01805157],
       [-0.00852774, -0.0074516 , -0.00938685, ...,  0.03109682,
         0.02803863,  0.02216476],
       [ 0.01804893,  0.01868969,  0.01673115, ...,  0.02910084,
         0.02275218,  0.01410023],
       ...,
       [ 0.00599336,  0.00685579,  0.00523005, ...,  0.03572195,
         0.03191466,  0.02628002],
       [-0.00654212, -0.00580352, -0.00686528, ...,  0.0299112 ,
         0.0266614 ,  0.02060995],
       [ 0.00831333,  0.00815701,  0.00666449, ...,  0.02978874,
         0.02618942,  0.02271046]])

In [59]:
data_scaled = pd.DataFrame(X_scaled, columns=flux_columns)
data_scaled['LABEL'] = y.values

data_scaled

FLUX.1    FLUX.2    FLUX.3    FLUX.4    FLUX.5    FLUX.6    FLUX.7  \
0    -0.002356 -0.002054 -0.005798 -0.008237 -0.008479 -0.011271 -0.010440   
1    -0.008528 -0.007452 -0.009387 -0.008827 -0.010201 -0.009118 -0.008426   
2     0.018049  0.018690  0.016731  0.015328  0.013010  0.013236  0.014403   
3     0.008464  0.010040  0.007084  0.006386  0.007001  0.006876  0.008513   
4    -0.058207 -0.056947 -0.057783 -0.056283 -0.052582 -0.049016 -0.046199   
...        ...       ...       ...       ...       ...       ...       ...   
5082 -0.010994 -0.010165 -0.010310 -0.011402 -0.009711 -0.008928 -0.007967   
5083  0.039305  0.034982  0.034750  0.031293  0.025949  0.019450  0.019841   
5084  0.005993  0.006856  0.005230  0.003636  0.005397  0.004893  0.005637   
5085 -0.006542 -0.005804 -0.006865 -0.007153 -0.006693 -0.006128 -0.004681   
5086  0.008313  0.008157  0.006664  0.005916  0.004061  0.002960  0.002984   

        FLUX.8    FLUX.9   FLUX.10  ...  FLUX.3189  FLUX.3190  FLUX.3191  \
0    -0.009202 -0.009644 -0.015512  ...  -0.016832  -0.017778  -0.014490   
1    -0.008724 -0.009838 -0.011043  ...  -0.014863  -0.016170  -0.015495   
2     0.016237  0.014920  0.017677  ...  -0.013581  -0.015124  -0.015595   
3     0.008593  0.009016  0.009384  ...  -0.014061  -0.015515  -0.014392   
4    -0.049650 -0.052911 -0.057256  ...  -0.025265  -0.024664  -0.022167   
...        ...       ...       ...  ...        ...        ...        ...   
5082 -0.007149 -0.007314 -0.007876  ...  -0.009810  -0.011821  -0.011870   
5083  0.015035  0.017597  0.012525  ...  -0.014092  -0.017184  -0.015755   
5084  0.006129  0.005457  0.005016  ...  -0.015473  -0.016550  -0.014373   
5085 -0.005000 -0.005688 -0.006941  ...  -0.014047  -0.015547  -0.015087   
5086  0.002813 -0.000187 -0.000536  ...  -0.013929  -0.014161  -0.015028   

      FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  LABEL  
0     -0.012684  -0.010540   0.029934   0.034198   0.027368   0.018052      2  
1     -0.013734  -0.012259   0.027075   0.031097   0.028039   0.022165      2  
2     -0.014049  -0.012178   0.027069   0.029101   0.022752   0.014100      2  
3     -0.013245  -0.012510   0.027239   0.029755   0.025989   0.021753      2  
4     -0.022363  -0.020486   0.005329   0.009026   0.001748  -0.014525      2  
...         ...        ...        ...        ...        ...        ...    ...  
5082  -0.010565  -0.009431   0.026360   0.029773   0.027254   0.022120      1  
5083  -0.016663  -0.014823   0.029862   0.036391   0.024250   0.023247      1  
5084  -0.013325  -0.012338   0.031414   0.035722   0.031915   0.026280      1  
5085  -0.013832  -0.012301   0.027470   0.029911   0.026661   0.020610      1  
5086  -0.013747  -0.012747   0.025415   0.029789   0.026189   0.022710      1  

[5087 rows x 3198 columns]

In [66]:
X_train, X_val, y_train, y_val = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [61]:
X_train_reshaped = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_val_reshaped = X_val.reshape((X_val.shape[0], X_val.shape[1], 1))

In [85]:
X_train_reshaped.shape,X_val_reshaped.shape

((4069, 3197, 1), (1018, 3197, 1))

In [89]:
onehot_encoder = OneHotEncoder(sparse_output=False)
y_train_encoded = onehot_encoder.fit_transform(y_train.values.reshape(-1, 1))
y_val_encoded = onehot_encoder.transform(y_val.values.reshape(-1, 1))

In [65]:
print("원-핫 인코딩된 훈련 레이블:")
print(y_train_encoded[:5])
print("원-핫 인코딩된 검증 레이블:")
print(y_val_encoded[:5])

원-핫 인코딩된 훈련 레이블:
[[0]
 [0]
 [0]
 [0]
 [0]]
원-핫 인코딩된 검증 레이블:
[[0]
 [0]
 [1]
 [0]
 [0]]


In [73]:
X_train

array([[-0.0067923 , -0.00609946, -0.00691868, ...,  0.02989145,
         0.02585694,  0.01994944],
       [-0.00875374, -0.00680512, -0.00590458, ...,  0.03443587,
         0.02187828,  0.00481841],
       [-0.3389584 , -0.66279978, -0.23375196, ...,  0.46790264,
         0.31855584, -0.24733304],
       ...,
       [-0.00685833, -0.00677759, -0.00715692, ...,  0.03123113,
         0.02637993,  0.02224015],
       [-0.00630077, -0.00609625, -0.00651706, ...,  0.03071535,
         0.02693611,  0.02075381],
       [-0.01198608, -0.01523641, -0.01208642, ...,  0.02428328,
         0.01637366,  0.02270701]])

In [74]:
y_train

2222    1
2194    1
668     1
1918    1
3076    1
       ..
4426    1
466     1
3092    1
3772    1
860     1
Name: LABEL, Length: 4069, dtype: int64

In [75]:
X_val

array([[-0.00756841, -0.0069836 , -0.0076658 , ...,  0.02952295,
         0.0262226 ,  0.0194473 ],
       [-0.00814038, -0.00833804, -0.00954066, ...,  0.02596099,
         0.02330897,  0.01825561],
       [-0.00471692, -0.00375534, -0.00537196, ...,  0.0317582 ,
         0.03020249,  0.0214579 ],
       ...,
       [-0.00704573, -0.00601503, -0.00687761, ...,  0.03064706,
         0.02762073,  0.02059059],
       [-0.00200215, -0.00111988, -0.0019157 , ...,  0.03179262,
         0.02692627,  0.02209145],
       [-0.00654212, -0.00580352, -0.00686528, ...,  0.0299112 ,
         0.0266614 ,  0.02060995]])

In [76]:
y_val

589     1
1029    1
33      2
2133    1
2153    1
       ..
1832    1
3131    1
3482    1
517     1
5085    1
Name: LABEL, Length: 1018, dtype: int64